(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurOfflineRecoveryStore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const clone=v=>JSON.parse(JSON.stringify(v));function canonical(v){if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v);}function checksum(v){let h=2166136261,s=canonical(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
class MemoryAdapter{constructor(limit=Infinity){this.limit=limit;this.map=new Map();}async put(k,v){const bytes=canonical(v).length;if(bytes>this.limit){const e=new Error('RECOVERY_QUOTA_EXCEEDED');e.name='QuotaExceededError';throw e;}this.map.set(k,clone(v));}async get(k){return this.map.has(k)?clone(this.map.get(k)):null;}async delete(k){this.map.delete(k);}async keys(){return[...this.map.keys()];}}
class OfflineRecoveryStore{constructor(options={}){this.adapter=options.adapter||new MemoryAdapter();this.clock=options.clock||(()=>new Date().toISOString());this.quarantine=[];}
 async save(project,id='latest'){const payload=clone(project);const record={schema:'plmr-offline-recovery-v1',id:String(id),savedAt:this.clock(),payload,checksum:checksum(payload)};try{await this.adapter.put(record.id,record);}catch(e){if(e&&e.name==='QuotaExceededError')throw new Error('RECOVERY_QUOTA_EXCEEDED');throw e;}return clone(record);}
 async inspect(id='latest'){const r=await this.adapter.get(String(id));if(!r)return{status:'MISSING',id:String(id)};if(!r.payload||r.checksum!==checksum(r.payload)){this.quarantine.push({id:String(id),reason:'CHECKSUM',record:clone(r)});await this.adapter.delete(String(id));return{status:'CORRUPT',id:String(id),quarantined:true};}return{status:'READY',id:r.id,savedAt:r.savedAt,checksum:r.checksum,payload:clone(r.payload)};}
 async dryRun(id,current){const x=await this.inspect(id);if(x.status!=='READY')return{schema:'plmr-recovery-dry-run-v1',status:x.status,ready:false,mutated:false};return{schema:'plmr-recovery-dry-run-v1',status:'READY',ready:true,mutated:false,currentChecksum:checksum(current||{}),recoveryChecksum:x.checksum,payload:clone(x.payload),requiresConfirmation:true};}
 async restore(plan,options={}){if(!plan||plan.schema!=='plmr-recovery-dry-run-v1'||plan.ready!==true)throw new Error('RECOVERY_PLAN_NOT_READY');if(options.confirmed!==true)throw new Error('RECOVERY_CONFIRMATION_REQUIRED');return clone(plan.payload);}
 async list(){return this.adapter.keys();}}
return Object.freeze({canonical,checksum,MemoryAdapter,OfflineRecoveryStore});});
