(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurRevisionDiff=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const clone=v=>JSON.parse(JSON.stringify(v));
function stable(v){if(Array.isArray(v))return'['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v);}
function hash(v){let h=2166136261,s=stable(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
function equal(a,b,tol){if(typeof a==='number'&&typeof b==='number')return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=tol;return stable(a)===stable(b);}
function objectDiff(a={},b={},tol=0){const added=[],removed=[],changed=[];for(const k of new Set([...Object.keys(a||{}),...Object.keys(b||{})])){if(!(k in (a||{})))added.push({key:k,value:clone(b[k])});else if(!(k in (b||{})))removed.push({key:k,value:clone(a[k])});else if(!equal(a[k],b[k],tol))changed.push({key:k,before:clone(a[k]),after:clone(b[k])});}return{added,removed,changed};}
function entityMap(list){return new Map((list||[]).filter(e=>e&&e.id).map(e=>[String(e.id),e]));}
function compare(before={},after={},options={}){const tol=Number(options.tolerance)||0;const parameters=objectDiff(before.parameters,after.parameters,tol),a=entityMap(before.entities),b=entityMap(after.entities),added=[],removed=[],changed=[];for(const id of new Set([...a.keys(),...b.keys()])){if(!a.has(id))added.push(clone(b.get(id)));else if(!b.has(id))removed.push(clone(a.get(id)));else{const d=objectDiff(a.get(id),b.get(id),tol);if(d.added.length||d.removed.length||d.changed.length)changed.push({id,diff:d});}}const result={schema:'plmr-revision-diff-v1',beforeRevision:before.revision??null,afterRevision:after.revision??null,parameters,entities:{added,removed,changed},visual:{beforeHash:hash(before.visualSnapshot||before.entities||[]),afterHash:hash(after.visualSnapshot||after.entities||[])},readOnly:true,tolerance:tol};result.summary={added:parameters.added.length+added.length,removed:parameters.removed.length+removed.length,changed:parameters.changed.length+changed.length};return Object.freeze(result);}
function screenshotEvidence(diff,beforePngHash,afterPngHash){return Object.freeze({schema:'plmr-revision-visual-evidence-v1',diffSummary:clone(diff.summary),beforePngHash:String(beforePngHash||''),afterPngHash:String(afterPngHash||''),sameVisual:String(beforePngHash||'')===String(afterPngHash||''),authoritative:false});}
return Object.freeze({stable,hash,equal,objectDiff,compare,screenshotEvidence});});
