(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurParametricDimensionEditor=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=v=>JSON.parse(JSON.stringify(v));
function finitePositive(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error('DIMENSION_VALUE_INVALID');return n;}
class ParametricDimensionEditor{
 constructor(options={}){this.mappings=new Map();this.validate=options.validate||(()=>({ok:true}));this.transaction=options.transaction||((label,fn)=>fn());this.exportSignature=options.exportSignature||null;}
 register(def){if(!def||!def.dimensionId||!def.parameter)throw new Error('DIMENSION_MAPPING_INVALID');if(this.mappings.has(def.dimensionId))throw new Error('DIMENSION_MAPPING_DUPLICATE');const x=Object.freeze({views:Object.freeze([...(def.views||[])]),min:def.min??0,max:def.max??Infinity,...def});this.mappings.set(def.dimensionId,x);return x;}
 plan(dimensionId,value,project){const m=this.mappings.get(dimensionId);if(!m)throw new Error('DIMENSION_MAPPING_UNKNOWN');const n=finitePositive(value);if(n<m.min||n>m.max)throw new Error('DIMENSION_RANGE_INVALID');const before=clone(project);const after=clone(project);after.parameters={...(after.parameters||{}),[m.parameter]:n};const check=this.validate(after,{mapping:m,value:n});if(check===false||(check&&check.ok===false))throw new Error(`DIMENSION_CONSTRAINT_INVALID${check&&check.code?':'+check.code:''}`);return Object.freeze({schema:'plmr-parametric-dimension-plan-v1',dimensionId,parameter:m.parameter,value:n,before,after,dirtyViews:Object.freeze([...m.views]),requiresConfirmation:true});}
 apply(plan,options={}){if(!plan||plan.schema!=='plmr-parametric-dimension-plan-v1')throw new Error('DIMENSION_PLAN_REQUIRED');if(options.confirmed!==true)throw new Error('DIMENSION_CONFIRMATION_REQUIRED');const beforeSig=this.exportSignature?this.exportSignature(plan.before):null;return this.transaction(`Ölçü: ${plan.dimensionId}`,()=>{const result=clone(plan.after);return Object.freeze({project:result,undo:()=>clone(plan.before),dirtyViews:[...plan.dirtyViews],beforeExportSignature:beforeSig});});}
 applyMany(edits,project,options={}){let cursor=clone(project),plans=[];for(const e of edits||[]){const plan=this.plan(e.dimensionId,e.value,cursor);plans.push(plan);cursor=clone(plan.after);}if(options.confirmed!==true)throw new Error('DIMENSION_CONFIRMATION_REQUIRED');return this.transaction('Toplu ölçü düzenleme',()=>Object.freeze({project:cursor,undo:()=>clone(project),dirtyViews:[...new Set(plans.flatMap(p=>p.dirtyViews))],plans:Object.freeze(plans)}));}
}
return Object.freeze({finitePositive,ParametricDimensionEditor});});
