(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurComponentCatalog=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const SCHEMA='plmr-component-catalog-v1';const clone=v=>JSON.parse(JSON.stringify(v));
function compareVersion(a,b){const pa=String(a||'0').split('.').map(Number),pb=String(b||'0').split('.').map(Number);for(let i=0;i<Math.max(pa.length,pb.length);i++){const d=(pa[i]||0)-(pb[i]||0);if(d)return d>0?1:-1;}return 0;}
function normalize(c){if(!c||!c.code||!c.version||!c.type)throw new Error('CATALOG_COMPONENT_INVALID');return Object.freeze({schema:SCHEMA,code:String(c.code).trim().toUpperCase(),version:String(c.version),type:String(c.type).trim().toUpperCase(),description:String(c.description||''),asset:c.asset?String(c.asset):null,unit:String(c.unit||'ADET').toUpperCase(),compatibleProducts:Object.freeze((c.compatibleProducts||['*']).map(x=>String(x).toUpperCase())),compatibleWith:Object.freeze([...(c.compatibleWith||[]).map(x=>String(x).toUpperCase())]),metadata:Object.freeze(clone(c.metadata||{}))});}
class ComponentCatalog{constructor(){this.byCode=new Map();}
 add(input){const c=normalize(input);const list=this.byCode.get(c.code)||[];if(list.some(x=>x.version===c.version))throw new Error('CATALOG_VERSION_DUPLICATE');list.push(c);list.sort((a,b)=>compareVersion(b.version,a.version));this.byCode.set(c.code,list);return c;}
 get(code,version){const list=this.byCode.get(String(code||'').toUpperCase())||[];const c=version?list.find(x=>x.version===String(version)):list[0];return c?clone(c):null;}
 resolve(code,options={}){const c=this.get(code,options.version);if(!c)return Object.freeze({ok:false,code:'COMPONENT_MISSING',requested:String(code||'')});const product=String(options.productType||'*').toUpperCase();if(!c.compatibleProducts.includes('*')&&!c.compatibleProducts.includes(product))return Object.freeze({ok:false,code:'COMPONENT_PRODUCT_INCOMPATIBLE',component:c});if(options.installedVersion&&compareVersion(c.version,options.installedVersion)>0)return Object.freeze({ok:false,code:'COMPONENT_VERSION_UNAVAILABLE',component:c});if(options.requireAsset&&(!c.asset||options.assetExists&&options.assetExists(c.asset)!==true))return Object.freeze({ok:false,code:'COMPONENT_ASSET_MISSING',component:c,fallback:{shape:'BOUNDING_BOX',label:c.code}});return Object.freeze({ok:true,component:c});}
 validateSet(codes){const resolved=codes.map(x=>this.get(x));if(resolved.some(x=>!x))return{ok:false,code:'COMPONENT_MISSING'};const names=new Set(resolved.map(x=>x.code));for(const c of resolved)for(const need of c.compatibleWith)if(!names.has(need))return{ok:false,code:'COMPONENT_DEPENDENCY_MISSING',component:c.code,required:need};return{ok:true,components:resolved};}
 bom(items){const rows=new Map();for(const item of items||[]){const r=this.resolve(item.code,{version:item.version,productType:item.productType});if(!r.ok)throw new Error(r.code);const key=`${r.component.code}@${r.component.version}`;const row=rows.get(key)||{code:r.component.code,version:r.component.version,description:r.component.description,unit:r.component.unit,quantity:0};row.quantity+=Number(item.quantity)||1;rows.set(key,row);}return Object.freeze([...rows.values()].sort((a,b)=>a.code.localeCompare(b.code)));}
 exportSnapshot(){return Object.freeze({schema:SCHEMA,components:[...this.byCode.values()].flat().map(clone).sort((a,b)=>a.code.localeCompare(b.code)||compareVersion(b.version,a.version))});}}
return Object.freeze({SCHEMA,compareVersion,normalize,ComponentCatalog});});
