(function(root,factory){const api=factory(typeof require==='function'?require:null);if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurBrowserSecurity=api;})(typeof globalThis!=='undefined'?globalThis:this,function(req){'use strict';
const BLOCKED_KEYS=new Set(['__proto__','prototype','constructor']);
const SECRET_PATTERNS=[/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/i,/(?:service_role|secret|api[_-]?key|access[_-]?token)\s*[:=]\s*["']?[A-Za-z0-9._-]{16,}/i,/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/];
function safeString(value){return String(value??'').replace(/<\s*script\b[^>]*>[\s\S]*?<\s*\/\s*script\s*>/gi,'').replace(/\bon[a-z]+\s*=\s*(["']).*?\1/gi,'').replace(/javascript\s*:/gi,'blocked:').replace(/<\/?(?:iframe|object|embed|link|meta)\b[^>]*>/gi,'');}
function sanitize(value,seen=new WeakSet()){if(value===null||typeof value==='number'||typeof value==='boolean')return value;if(typeof value==='string')return safeString(value);if(Array.isArray(value))return value.map(v=>sanitize(v,seen));if(typeof value!=='object')return null;if(seen.has(value))throw new Error('CYCLIC_INPUT_REJECTED');seen.add(value);const out=Object.create(null);for(const [k,v] of Object.entries(value)){if(BLOCKED_KEYS.has(k))continue;out[safeString(k)]=sanitize(v,seen);}seen.delete(value);return out;}
function inspectPlmr(input,{maxBytes=10*1024*1024}={}){const raw=typeof input==='string'?input:JSON.stringify(input);if(Buffer&&Buffer.byteLength(raw,'utf8')>maxBytes)throw new Error('PLMR_FILE_TOO_LARGE');let parsed;try{parsed=typeof input==='string'?JSON.parse(input):input;}catch(_){throw new Error('PLMR_JSON_INVALID');}const clean=sanitize(parsed);const schema=clean&&clean.schema;if(typeof schema!=='string'||!/^plmr-|^bcube-|^p3dv-|^project-model-/.test(schema))throw new Error('PLMR_SCHEMA_UNTRUSTED');return clean;}
function buildCsp({mode='report-only',reportUri='/csp-report',allowCdn=false}={}){if(!['report-only','enforce'].includes(mode))throw new Error('CSP_MODE_INVALID');const script=["'self'"];const style=["'self'","'unsafe-inline'"];if(allowCdn){script.push('https://cdn.jsdelivr.net','https://cdnjs.cloudflare.com');style.push('https://cdn.jsdelivr.net');}const directives=["default-src 'self'",`script-src ${script.join(' ')}`,`style-src ${style.join(' ')}`,"img-src 'self' data: blob:","font-src 'self' data:","connect-src 'self' https://*.supabase.co wss://*.supabase.co","object-src 'none'","base-uri 'self'","frame-ancestors 'none'","form-action 'self'","worker-src 'self' blob:","trusted-types plmr-html","require-trusted-types-for 'script'",`report-uri ${reportUri}`];return{mode,header:mode==='enforce'?'Content-Security-Policy':'Content-Security-Policy-Report-Only',value:directives.join('; '),rollout:mode==='report-only'?'OBSERVE':'ENFORCE'};}
function trustedTypesFeasibility(env=globalThis){return{supported:!!(env&&env.trustedTypes&&typeof env.trustedTypes.createPolicy==='function'),policyName:'plmr-html',fallback:'textContent-and-sanitized-templates',enforcementReady:false};}
function sri(value,algorithm='sha384'){if(!['sha256','sha384','sha512'].includes(algorithm))throw new Error('SRI_ALGORITHM_INVALID');if(!req)throw new Error('SRI_NODE_CRYPTO_REQUIRED');const crypto=req('crypto');return`${algorithm}-${crypto.createHash(algorithm).update(value).digest('base64')}`;}
function verifySri(value,expected){const alg=String(expected).split('-',1)[0];return sri(value,alg)===expected;}
function auditDependencies(pkg,lock){const issues=[];for(const area of ['dependencies','devDependencies'])for(const [name,version] of Object.entries(pkg&&pkg[area]||{})){if(!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(String(version)))issues.push({code:'UNPINNED_DEPENDENCY',name,version});if(lock&&lock.packages&&!lock.packages[`node_modules/${name}`])issues.push({code:'LOCK_ENTRY_MISSING',name});}return{ok:issues.length===0,issues};}
function scanSecrets(files){const findings=[];for(const [name,content] of Object.entries(files||{}))for(const pattern of SECRET_PATTERNS)if(pattern.test(String(content)))findings.push({file:name,code:'POSSIBLE_SECRET'});return{ok:findings.length===0,findings};}
return Object.freeze({safeString,sanitize,inspectPlmr,buildCsp,trustedTypesFeasibility,sri,verifySri,auditDependencies,scanSecrets});});
