(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurBomEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const UNITS=new Set(['pcs','mm','m','m2']);const clone=v=>JSON.parse(JSON.stringify(v??null));
function normalize(item){if(!item||!item.code)throw new Error('BOM_CODE_REQUIRED');const unit=String(item.unit||'pcs');if(!UNITS.has(unit))throw new Error(`BOM_UNIT_INVALID:${unit}`);const quantity=Number(item.quantity??1);if(!(quantity>0&&Number.isFinite(quantity)))throw new Error('BOM_QUANTITY_INVALID');const lengthMm=item.lengthMm==null?null:Number(item.lengthMm);if(lengthMm!=null&&!(lengthMm>0&&Number.isFinite(lengthMm)))throw new Error('BOM_LENGTH_INVALID');return{code:String(item.code),description:String(item.description||''),unit,quantity,lengthMm,sourceRefs:[...new Set([].concat(item.sourceRefs||item.sourceRef||[]).filter(Boolean).map(String))].sort(),productType:item.productType?String(item.productType):null};}
function key(x){return[x.code,x.unit,x.lengthMm??'',x.productType??''].join('|');}
function generate(items,{verifiedProducts=[]}={}){const allowed=new Set(verifiedProducts);const map=new Map();for(const raw of items||[]){const x=normalize(raw);if(allowed.size&&(!x.productType||!allowed.has(x.productType)))throw new Error(`BOM_PRODUCT_UNVERIFIED:${x.productType||'NONE'}`);const k=key(x);if(!map.has(k))map.set(k,{...x});else{const r=map.get(k);r.quantity+=x.quantity;r.sourceRefs=[...new Set(r.sourceRefs.concat(x.sourceRefs))].sort();}}const lines=[...map.values()].sort((a,b)=>a.code.localeCompare(b.code,'en')||(a.lengthMm||0)-(b.lengthMm||0));const totals={pieces:0,lengthMm:0,lengthM:0,areaM2:0};for(const x of lines){if(x.unit==='pcs')totals.pieces+=x.quantity;if(x.unit==='mm')totals.lengthMm+=x.quantity;if(x.unit==='m')totals.lengthM+=x.quantity;if(x.unit==='m2')totals.areaM2+=x.quantity;if(x.lengthMm!=null)totals.lengthMm+=x.lengthMm*x.quantity;}totals.lengthM+=totals.lengthMm/1000;return{schema:'plmr-bom-v1',lines,totals,traceable:lines.every(x=>x.sourceRefs.length>0)};}
function cutList(bom,{stockLengthMm=6000}={}){if(!(stockLengthMm>0))throw new Error('STOCK_LENGTH_INVALID');const cuts=[];for(const line of bom.lines||[]){if(line.lengthMm==null)continue;for(let i=0;i<line.quantity;i++)cuts.push({code:line.code,lengthMm:line.lengthMm,stockLengthMm,wasteMm:stockLengthMm-line.lengthMm,sourceRefs:[...line.sourceRefs]});}if(cuts.some(x=>x.wasteMm<0))throw new Error('CUT_EXCEEDS_STOCK');return cuts;}
function csvCell(v){let s=String(v??'');if(/^[=+\-@]/.test(s))s="'"+s;if(/[",\r\n]/.test(s))s='"'+s.replaceAll('"','""')+'"';return s;}
function toCsv(bom){const rows=[['Kod','Açıklama','Birim','Adet','Boy (mm)','Kaynak']].concat((bom.lines||[]).map(x=>[x.code,x.description,x.unit,x.quantity,x.lengthMm??'',x.sourceRefs.join('|')]));return'\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')+'\r\n';}
function toPdfPayload(bom,project={}){return{schema:'plmr-production-form-pdf-v1',title:'PLMR ÜRETİM FORMU',project:{code:String(project.code||''),revision:String(project.revision||'')},columns:['Kod','Açıklama','Birim','Adet','Boy (mm)','Kaynak'],rows:(bom.lines||[]).map(x=>[x.code,x.description,x.unit,x.quantity,x.lengthMm??'',x.sourceRefs.join(', ')]),totals:clone(bom.totals)};}
return Object.freeze({UNITS,normalize,generate,cutList,csvCell,toCsv,toPdfPayload});});
