(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurTelemetryService=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const ALLOWED_EVENTS=Object.freeze({TASK_STARTED:['task','surface'],TASK_COMPLETED:['task','surface','durationBucket','success'],ERROR_OCCURRED:['code','surface'],FEATURE_USED:['feature','surface']});const BLOCKED=/(name|email|phone|customer|project|token|secret|geometry|entity|coordinate|width|height|drawing|description)/i;const clone=v=>JSON.parse(JSON.stringify(v??null));
function validateEvent(event){if(!event||!ALLOWED_EVENTS[event.type])throw new Error('TELEMETRY_EVENT_TYPE_INVALID');const allowed=new Set(ALLOWED_EVENTS[event.type]);const props={};for(const [k,v] of Object.entries(event.properties||{})){if(BLOCKED.test(k))throw new Error(`TELEMETRY_SENSITIVE_FIELD:${k}`);if(!allowed.has(k))throw new Error(`TELEMETRY_FIELD_DENIED:${k}`);if(!['string','number','boolean'].includes(typeof v)&&v!==null)throw new Error(`TELEMETRY_VALUE_INVALID:${k}`);props[k]=v;}return{schema:'plmr-telemetry-event-v1',type:event.type,timestamp:event.timestamp||null,properties:props};}
class TelemetryService{constructor({consent=false,online=()=>true,sender=async()=>({ok:true}),limit=500}={}){this.consent=consent===true;this.online=online;this.sender=sender;this.limit=limit;this.queue=[];this.sent=[];}
 setConsent(value){this.consent=value===true;if(!this.consent)this.purge();return this.consent;}
 track(event){if(!this.consent)return{status:'IGNORED_NO_CONSENT'};const clean=validateEvent(event);this.queue.push(clean);if(this.queue.length>this.limit)this.queue.splice(0,this.queue.length-this.limit);return{status:'QUEUED',size:this.queue.length};}
 async flush(){if(!this.consent)throw new Error('TELEMETRY_CONSENT_REQUIRED');if(!this.online())return{status:'OFFLINE',remaining:this.queue.length};let sent=0;while(this.queue.length){const event=this.queue[0];const r=await this.sender(clone(event));if(!r||r.ok!==true)break;this.sent.push(event);this.queue.shift();sent++;}return{status:this.queue.length?'PARTIAL':'FLUSHED',sent,remaining:this.queue.length};}
 purge(){const count=this.queue.length+this.sent.length;this.queue.length=0;this.sent.length=0;return{status:'PURGED',count};}
 dashboard(){const all=this.sent.concat(this.queue),byType={},tasks={started:0,completed:0,success:0};for(const e of all){byType[e.type]=(byType[e.type]||0)+1;if(e.type==='TASK_STARTED')tasks.started++;if(e.type==='TASK_COMPLETED'){tasks.completed++;if(e.properties.success===true)tasks.success++;}}return{schema:'plmr-telemetry-dashboard-v1',eventCount:all.length,byType,tasks,completionRate:tasks.started?tasks.completed/tasks.started:0,successRate:tasks.completed?tasks.success/tasks.completed:0};}}
return Object.freeze({ALLOWED_EVENTS,validateEvent,TelemetryService});});
