(function(root,factory){const api=factory(root.PulumurProductRegistry,root.PulumurStandaloneProject);if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurBulkPositionImport=api;})(typeof globalThis!=='undefined'?globalThis:this,function(defaultRegistry,defaultModel){
'use strict';
const HEADER_ALIASES={positionNo:['POZ NO','POZ','POSITIONNO','POSITION NO'],productType:['URUN','ÜRÜN','PRODUCT','PRODUCTTYPE'],width:['GENISLIK','GENİŞLİK','WIDTH'],height:['YUKSEKLIK','YÜKSEKLİK','HEIGHT'],quantity:['ADET','QUANTITY','QTY'],options:['OPSIYONLAR','OPSİYONLAR','OPTIONS'],description:['ACIKLAMA','AÇIKLAMA','DESCRIPTION']};
const PRODUCT_ALIASES={SURME:'SLIDING','SÜRME':'SLIDING',SLIDING:'SLIDING',GIYOTIN:'GUILLOTINE','GİYOTİN':'GUILLOTINE',GUILLOTINE:'GUILLOTINE',ZIP:'ZIP_SCREEN','ZIP PERDE':'ZIP_SCREEN',ZIP_SCREEN:'ZIP_SCREEN','ZIP SCREEN':'ZIP_SCREEN'};
function norm(v){return String(v==null?'':v).trim().toUpperCase().replace(/[İIı]/g,'I').replace(/Ş/g,'S').replace(/Ğ/g,'G').replace(/Ü/g,'U').replace(/Ö/g,'O').replace(/Ç/g,'C').replace(/[_-]+/g,' ').replace(/\s+/g,' ');}function detectDelimiter(text){const first=String(text).split(/\r?\n/).find(x=>x.trim())||'';return [';','\t',','].sort((a,b)=>(first.split(b).length-first.split(a).length))[0];}
function parseDelimited(text,delimiter){const d=delimiter||detectDelimiter(text),rows=[];let row=[],field='',quote=false;const s=String(text||'');for(let i=0;i<=s.length;i++){const ch=s[i]??'\n';if(quote){if(ch==='"'&&s[i+1]==='"'){field+='"';i++;}else if(ch==='"')quote=false;else field+=ch;}else if(ch==='"')quote=true;else if(ch===d){row.push(field);field='';}else if(ch==='\n'){row.push(field.replace(/\r$/,''));field='';if(row.some(v=>String(v).trim()))rows.push(row);row=[];}else field+=ch;}if(quote)throw new Error('CSV_UNCLOSED_QUOTE');return rows;}
function headerMap(header){const map={};header.forEach((value,index)=>{const key=norm(value);for(const [name,aliases] of Object.entries(HEADER_ALIASES))if(aliases.map(norm).includes(key))map[name]=index;});return map;}
function parseOptions(value){const text=String(value||'').trim();if(!text)return{};if(text.startsWith('{')){const parsed=JSON.parse(text);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('OPTIONS_JSON_OBJECT_REQUIRED');return parsed;}const out={};text.split(/[|,]/).filter(Boolean).forEach(part=>{const [key,...rest]=part.split('=');if(!key||!rest.length)throw new Error(`OPTION_FORMAT:${part}`);let v=rest.join('=').trim();if(/^-?\d+(\.\d+)?$/.test(v))v=Number(v);else if(/^(true|false)$/i.test(v))v=/^true$/i.test(v);out[key.trim()]=v;});return out;}
function canonicalProduct(value,registry){const n=norm(value);if(PRODUCT_ALIASES[n])return PRODUCT_ALIASES[n];try{return registry&&registry.resolveId?registry.resolveId(value):n.replace(/ /g,'_');}catch(_){return n.replace(/ /g,'_');}}
function fromRows(rows,options){if(!Array.isArray(rows)||rows.length<2)throw new Error('IMPORT_ROWS_REQUIRED');const map=headerMap(rows[0]);for(const key of ['positionNo','productType','width','height'])if(map[key]==null)throw new Error(`IMPORT_HEADER_MISSING:${key}`);const existing=new Set((options&&options.existingPositions||[]).map(p=>norm(p.positionNo)));const seen=new Set();const model=options&&options.model||defaultModel,registry=options&&options.registry||defaultRegistry;const results=[];rows.slice(1).forEach((cells,index)=>{const sourceLine=index+2,errors=[];const positionNo=String(cells[map.positionNo]||'').trim();const productType=canonicalProduct(cells[map.productType],registry);const width=Number(String(cells[map.width]||'').replace(',','.'));const height=Number(String(cells[map.height]||'').replace(',','.'));const quantity=map.quantity==null?1:Number(cells[map.quantity]||1);let rowOptions={};try{rowOptions=map.options==null?{}:parseOptions(cells[map.options]);}catch(e){errors.push(e.message);}const key=norm(positionNo);if(!positionNo)errors.push('POZ_NUMARASI_BOS');if(existing.has(key)||seen.has(key))errors.push('POZ_NUMARASI_TEKRAR');if(!(width>0&&Number.isFinite(width)))errors.push('GENISLIK_GECERSIZ');if(!(height>0&&Number.isFinite(height)))errors.push('YUKSEKLIK_GECERSIZ');if(!(quantity>0&&Number.isInteger(quantity)))errors.push('ADET_GECERSIZ');let candidate={positionNo,productType,width,height,quantity,description:map.description==null?'':String(cells[map.description]||''),options:rowOptions};if(!errors.length&&model){try{const temp=model.createProject({positions:[candidate]});const valid=model.validateProject(temp);if(!valid.valid)errors.push(...valid.errors.map(e=>e.code||e.message));candidate=temp.positions[0];}catch(e){errors.push(e.message||String(e));}}seen.add(key);results.push({line:sourceLine,status:errors.length?'ERROR':'VALID',errors,candidate,source:cells});});return{schema:'plmr-bulk-position-dry-run-v1',createdAt:new Date(0).toISOString(),rows:results,validPositions:results.filter(r=>r.status==='VALID').map(r=>r.candidate),invalidRows:results.filter(r=>r.status==='ERROR'),canApply:results.some(r=>r.status==='VALID'),applied:false};}
function dryRun(text,options){return fromRows(parseDelimited(text),options);}
function apply(project,result,options){if(!project||!Array.isArray(project.positions))throw new Error('IMPORT_PROJECT_REQUIRED');if(!result||result.schema!=='plmr-bulk-position-dry-run-v1'||result.applied)throw new Error('IMPORT_DRY_RUN_REQUIRED');const allowPartial=Boolean(options&&options.allowPartial);if(result.invalidRows.length&&!allowPartial)throw new Error('IMPORT_HAS_INVALID_ROWS');const clone=JSON.parse(JSON.stringify(project));const model=options&&options.model||defaultModel;for(const item of result.validPositions){const type=item.productType;clone.positions.push(model?model.createPosition(type,item,clone.positions,model.commonDefaults(clone,type)):JSON.parse(JSON.stringify(item)));}if(model&&model.normalizeOrder)model.normalizeOrder(clone);result.applied=true;return clone;}
return{parseDelimited,headerMap,parseOptions,fromRows,dryRun,apply,canonicalProduct,detectDelimiter};
});
