(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurXlsxLite=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function u16(v,o){return v.getUint16(o,true)}function u32(v,o){return v.getUint32(o,true)}
function findEocd(view){for(let i=view.byteLength-22;i>=Math.max(0,view.byteLength-65557);i--)if(u32(view,i)===0x06054b50)return i;throw new Error('XLSX_ZIP_EOCD_NOT_FOUND');}
async function inflate(bytes,method){if(method===0)return bytes;if(method!==8)throw new Error('XLSX_ZIP_COMPRESSION_UNSUPPORTED');if(typeof process!=='undefined'&&process.versions&&process.versions.node){return new Uint8Array(require('zlib').inflateRawSync(Buffer.from(bytes)));}if(typeof DecompressionStream==='function'){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer());}throw new Error('XLSX_DEFLATE_UNAVAILABLE');}
async function unzip(buffer){const data=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer);const view=new DataView(data.buffer,data.byteOffset,data.byteLength);const eocd=findEocd(view);const total=u16(view,eocd+10),offset=u32(view,eocd+16);let cursor=offset;const files={};for(let i=0;i<total;i++){if(u32(view,cursor)!==0x02014b50)throw new Error('XLSX_ZIP_CENTRAL_INVALID');const method=u16(view,cursor+10),compressed=u32(view,cursor+20),nameLen=u16(view,cursor+28),extraLen=u16(view,cursor+30),commentLen=u16(view,cursor+32),local=u32(view,cursor+42);const name=new TextDecoder().decode(data.slice(cursor+46,cursor+46+nameLen));const localName=u16(view,local+26),localExtra=u16(view,local+28),start=local+30+localName+localExtra;files[name]=await inflate(data.slice(start,start+compressed),method);cursor+=46+nameLen+extraLen+commentLen;}return files;}
function decodeXml(bytes){return bytes?new TextDecoder('utf-8').decode(bytes):'';}function entities(s){return String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function sharedStrings(xml){const result=[];for(const m of xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)){const texts=Array.from(m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g),x=>entities(x[1]));result.push(texts.join(''));}return result;}
function columnIndex(ref){let n=0;for(const ch of String(ref||'').match(/[A-Z]+/i)?.[0]||'')n=n*26+ch.toUpperCase().charCodeAt(0)-64;return Math.max(0,n-1);}
function sheetRows(xml,shared){const rows=[];for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const row=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1],body=cm[2],ref=(attrs.match(/\br="([^"]+)"/)||[])[1],type=(attrs.match(/\bt="([^"]+)"/)||[])[1];let value='';if(type==='inlineStr'){value=Array.from(body.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g),x=>entities(x[1])).join('');}else{const raw=(body.match(/<v\b[^>]*>([\s\S]*?)<\/v>/)||[])[1]||'';value=type==='s'?(shared[Number(raw)]||''):entities(raw);}row[columnIndex(ref)]=value;}rows.push(row.map(v=>v==null?'':v));}return rows;}
async function parse(arrayBuffer){const files=await unzip(arrayBuffer);const shared=sharedStrings(decodeXml(files['xl/sharedStrings.xml']));const sheet=files['xl/worksheets/sheet1.xml']||Object.entries(files).find(([n])=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n))?.[1];if(!sheet)throw new Error('XLSX_WORKSHEET_NOT_FOUND');return sheetRows(decodeXml(sheet),shared);}
return{parse,unzip,sharedStrings,sheetRows};
});
