(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurIncrementalGeometryEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function canonical(v){if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v);}
function semanticEqual(a,b){return canonical(a)===canonical(b);}
class IncrementalGeometryEngine{
 constructor({compute,worker=null,clock=()=>Date.now(),debounceMs=40}={}){if(typeof compute!=='function')throw new Error('COMPUTE_REQUIRED');this.compute=compute;this.worker=worker;this.clock=clock;this.debounceMs=debounceMs;this.cache=new Map();this.dirty=new Set();this.generation=0;this.cancelled=new Set();this.pendingTimer=null;this.stats={hits:0,misses:0,discarded:0};}
 key(input){return canonical(input);}markDirty(ids){for(const id of [].concat(ids||[]))this.dirty.add(String(id));return this.dirty.size;}clearDirty(){this.dirty.clear();}
 cancel(generation=this.generation){this.cancelled.add(generation);if(this.pendingTimer){clearTimeout(this.pendingTimer);this.pendingTimer=null;}return generation;}
 async run(input,{preferWorker=true,force=false}={}){const generation=++this.generation;const key=this.key(input);if(!force&&this.dirty.size===0&&this.cache.has(key)){this.stats.hits++;return{generation,result:clone(this.cache.get(key)),source:'cache',accepted:true};}this.stats.misses++;const payload=clone(input);let result;if(preferWorker&&this.worker&&typeof this.worker.compute==='function'){try{result=await this.worker.compute(payload,{generation});}catch(_){result=await this.compute(payload,{generation,fallback:true});}}else result=await this.compute(payload,{generation});if(this.cancelled.has(generation)||generation!==this.generation){this.stats.discarded++;return{generation,result:null,source:'discarded',accepted:false};}this.cache.set(key,clone(result));this.clearDirty();return{generation,result:clone(result),source:preferWorker&&this.worker?'worker':'direct',accepted:true};}
 schedule(input,options={}){if(this.pendingTimer)clearTimeout(this.pendingTimer);return new Promise((resolve,reject)=>{this.pendingTimer=setTimeout(()=>{this.pendingTimer=null;this.run(input,options).then(resolve,reject);},this.debounceMs);});}
 invalidate(predicate){let n=0;for(const [k,v] of this.cache)if(!predicate||predicate(v,k)){this.cache.delete(k);n++;}return n;}
 snapshot(){return{generation:this.generation,dirty:[...this.dirty].sort(),cacheSize:this.cache.size,stats:{...this.stats}};}}
function createWorkerFallback(compute){return{async compute(input,ctx){const safe=typeof structuredClone==='function'?structuredClone(input):clone(input);return compute(safe,{...ctx,worker:true});}};}
return Object.freeze({canonical,semanticEqual,IncrementalGeometryEngine,createWorkerFallback});});
