(function(root,factory){const api=factory(root.PulumurStandaloneProject);if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurConstraintEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(defaultModel){
'use strict';
const EPSILON=0.01;const SEVERITY={ERROR:'ERROR',WARNING:'WARNING'};
function finite(v){return Number.isFinite(Number(v));}function violation(ruleId,severity,message,evidence,positionId){return{ruleId,severity,message,evidence:evidence||{},positionId:positionId||null};}
function normalizeBounds(b){if(!b)return null;const r={minX:Number(b.minX),minY:Number(b.minY),maxX:Number(b.maxX),maxY:Number(b.maxY)};if(!Object.values(r).every(Number.isFinite)||r.maxX<r.minX||r.maxY<r.minY)return null;r.width=r.maxX-r.minX;r.height=r.maxY-r.minY;return r;}
function overlaps(a,b,epsilon){const e=epsilon==null?EPSILON:Number(epsilon);return a.maxX-b.minX>e&&b.maxX-a.minX>e&&a.maxY-b.minY>e&&b.maxY-a.minY>e;}
function numericValues(entity){const out=[];['x','y','x1','y1','x2','y2','w','h','width','height','radius'].forEach(k=>{if(entity&&entity[k]!==undefined)out.push([k,entity[k]]);});for(const k of ['p1','p2','dimLine'])if(Array.isArray(entity&&entity[k]))entity[k].forEach((v,i)=>out.push([`${k}.${i}`,v]));if(Array.isArray(entity&&entity.points))entity.points.forEach((p,i)=>Array.isArray(p)&&p.forEach((v,j)=>out.push([`points.${i}.${j}`,v])));return out;}
function evaluateProject(project,options){const result=[];const model=options&&options.model||defaultModel;if(!project||!Array.isArray(project.positions)){result.push(violation('PROJECT_STRUCTURE',SEVERITY.ERROR,'Proje poz listesi bulunamadı.'));return result;}const seen=new Map();project.positions.forEach((p,index)=>{const id=p.id||null,label=String(p.positionNo||'').trim(),key=label.toUpperCase();if(!label)result.push(violation('POSITION_NUMBER_REQUIRED',SEVERITY.ERROR,`Satır ${index+1}: Poz numarası boş.`,{index},id));else if(seen.has(key))result.push(violation('POSITION_NUMBER_DUPLICATE',SEVERITY.ERROR,`${label}: Poz numarası tekrar ediyor.`,{first:seen.get(key),second:index},id));else seen.set(key,index);if(!finite(p.width)||Number(p.width)<=0||!finite(p.height)||Number(p.height)<=0)result.push(violation('POSITION_DIMENSIONS_FINITE',SEVERITY.ERROR,`${label||index+1}: Ölçüler pozitif ve sonlu olmalıdır.`,{width:p.width,height:p.height},id));if(!Number.isInteger(Number(p.quantity))||Number(p.quantity)<=0)result.push(violation('POSITION_QUANTITY',SEVERITY.ERROR,`${label||index+1}: Adet pozitif tam sayı olmalıdır.`,{quantity:p.quantity},id));});if(model&&typeof model.validateProject==='function'){try{const v=model.validateProject(project);for(const e of v.errors||[])result.push(violation(`PRODUCT_${e.code||'VALIDATION'}`,SEVERITY.ERROR,e.message,{source:'standalone-project'},e.id));}catch(e){result.push(violation('PRODUCT_VALIDATION_EXCEPTION',SEVERITY.ERROR,e.message||String(e)));}}return result;}
function evaluateDrawing(drawing,options){const result=[];if(!drawing||!Array.isArray(drawing.entities)){result.push(violation('DRAWING_STRUCTURE',SEVERITY.ERROR,'Çizim entity listesi bulunamadı.'));return result;}const bounds=normalizeBounds(drawing.bounds);if(!bounds)result.push(violation('DRAWING_BOUNDS',SEVERITY.ERROR,'Çizim bounds değeri geçersiz.',{bounds:drawing.bounds}));drawing.entities.forEach((entity,index)=>{numericValues(entity).forEach(([path,value])=>{if(!finite(value))result.push(violation('ENTITY_FINITE_COORDINATE',SEVERITY.ERROR,`Entity ${index} geçersiz koordinat içeriyor.`,{index,path,value},entity.positionId||entity.ownerInstance));});});const positions=Array.isArray(drawing.positions)?drawing.positions:[];for(let i=0;i<positions.length;i++){const a=normalizeBounds(positions[i].bounds);if(!a){result.push(violation('POSITION_BOUNDS',SEVERITY.ERROR,'Poz bounds değeri geçersiz.',{index:i},positions[i].position&&positions[i].position.id));continue;}for(let j=i+1;j<positions.length;j++){const b=normalizeBounds(positions[j].bounds);if(b&&overlaps(a,b,options&&options.epsilon)){const pa=positions[i].position||{},pb=positions[j].position||{};result.push(violation('POSITION_CLASH',SEVERITY.ERROR,`${pa.positionNo||i+1} ile ${pb.positionNo||j+1} çizimleri çakışıyor.`,{first:a,second:b,overlapX:Math.min(a.maxX,b.maxX)-Math.max(a.minX,b.minX),overlapY:Math.min(a.maxY,b.maxY)-Math.max(a.minY,b.minY)},pa.id));}}}
const namespaces=new Map();drawing.entities.forEach((e,index)=>{if(!e.entityNamespace)return;const owner=e.ownerInstance||e.positionId||'';const key=String(e.entityNamespace).toUpperCase();if(namespaces.has(key)&&namespaces.get(key)!==owner)result.push(violation('NAMESPACE_OWNER_CLASH',SEVERITY.ERROR,`${e.entityNamespace} namespace birden fazla poz sahibi tarafından kullanılıyor.`,{firstOwner:namespaces.get(key),secondOwner:owner,index},owner));else namespaces.set(key,owner);});return result;}
function evaluate(input,options){const findings=[];if(input&&input.project!==undefined)findings.push(...evaluateProject(input.project,options));if(input&&input.drawing!==undefined)findings.push(...evaluateDrawing(input.drawing,options));const unique=new Map();findings.forEach(f=>unique.set(`${f.ruleId}|${f.positionId||''}|${f.message}`,f));return Array.from(unique.values()).sort((a,b)=>a.severity.localeCompare(b.severity)||a.ruleId.localeCompare(b.ruleId)||String(a.positionId).localeCompare(String(b.positionId)));}
function assertExportable(input,options){const findings=evaluate(input,options),errors=findings.filter(f=>f.severity===SEVERITY.ERROR);if(errors.length){const error=new Error(`PLMR_CONSTRAINT_BLOCKED: ${errors.map(x=>`${x.ruleId}: ${x.message}`).join(' | ')}`);error.code='PLMR_CONSTRAINT_BLOCKED';error.findings=findings;throw error;}return findings;}
return{EPSILON,SEVERITY,normalizeBounds,overlaps,evaluateProject,evaluateDrawing,evaluate,assertExportable};
});
