(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurViewSyncService=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const SCHEMA='plmr-canonical-view-features-v1';const clone=v=>JSON.parse(JSON.stringify(v));
const FEATURE_VIEWS=Object.freeze({rails:['TOP','SIDE'],gutter:['TOP','FRONT','SIDE'],rearWall:['TOP','SIDE','REAR'],fabric:['TOP','SIDE'],profiles:['TOP','FRONT','SIDE','REAR']});
function normalizeFeature(name,value){if(!FEATURE_VIEWS[name])throw new Error('VIEW_FEATURE_UNKNOWN');if(value==null)return null;if(typeof value!=='object')throw new Error('VIEW_FEATURE_INVALID');return clone(value);}
function createCanonical(input={}){const features={};for(const name of Object.keys(FEATURE_VIEWS))features[name]=normalizeFeature(name,input.features&&input.features[name]);return{schema:SCHEMA,revision:Number(input.revision)||1,features};}
function derive(canonical,view){if(!canonical||canonical.schema!==SCHEMA)throw new Error('VIEW_CANONICAL_REQUIRED');const key=String(view||'').toUpperCase();if(!['TOP','FRONT','SIDE','REAR'].includes(key))throw new Error('VIEW_UNKNOWN');const features={};for(const [name,views] of Object.entries(FEATURE_VIEWS))if(views.includes(key)&&canonical.features[name]!=null)features[name]=clone(canonical.features[name]);return Object.freeze({schema:'plmr-derived-view-v1',view:key,sourceRevision:canonical.revision,features:Object.freeze(features)});}
function update(canonical,name,value){const next=createCanonical(canonical);next.features[name]=normalizeFeature(name,value);next.revision=(Number(canonical.revision)||0)+1;return Object.freeze({canonical:next,dirtyViews:Object.freeze([...(FEATURE_VIEWS[name]||[])])});}
function deriveAll(canonical){return Object.freeze({TOP:derive(canonical,'TOP'),FRONT:derive(canonical,'FRONT'),SIDE:derive(canonical,'SIDE'),REAR:derive(canonical,'REAR')});}
function migrateLegacy(project={}){if(project.canonicalViews&&project.canonicalViews.schema===SCHEMA)return{project:clone(project),migrated:false};const views=project.views||{};const pick=(feature)=>{for(const v of ['TOP','FRONT','SIDE','REAR'])if(views[v]&&views[v][feature]!=null)return clone(views[v][feature]);return null;};const canonical=createCanonical({features:Object.fromEntries(Object.keys(FEATURE_VIEWS).map(n=>[n,pick(n)]))});const next=clone(project);next.canonicalViews=canonical;return{project:next,migrated:true,legacyViewsPreserved:Boolean(project.views)};}
function consistency(canonical,derived){const expected=deriveAll(canonical);const errors=[];for(const view of Object.keys(expected))if(JSON.stringify(expected[view].features)!==JSON.stringify(derived[view]&&derived[view].features))errors.push(view);return Object.freeze({ok:errors.length===0,errors:Object.freeze(errors)});}
return Object.freeze({SCHEMA,FEATURE_VIEWS,createCanonical,derive,deriveAll,update,migrateLegacy,consistency});});
