(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurPluginSandbox=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const ALLOWED_PERMISSIONS=new Set(['project.read','selection.read','command.propose','diagnostics.write']);
function parseVersion(v){const m=String(v||'').match(/^(\d+)\.(\d+)\.(\d+)$/);if(!m)throw new Error('VERSION_INVALID');return m.slice(1).map(Number);}
function compatible(required,current){const r=parseVersion(required),c=parseVersion(current);return r[0]===c[0]&&(c[1]>r[1]||(c[1]===r[1]&&c[2]>=r[2]));}
function validateManifest(m,{hostVersion,authors=[],signatures=[]}={}){if(!m||m.schema!=='plmr-plugin-manifest-v1')throw new Error('PLUGIN_MANIFEST_INVALID');if(!/^[a-z0-9][a-z0-9.-]{2,63}$/.test(m.id||''))throw new Error('PLUGIN_ID_INVALID');if(!compatible(m.hostVersion,hostVersion))throw new Error('PLUGIN_VERSION_INCOMPATIBLE');if(!authors.includes(m.author))throw new Error('PLUGIN_AUTHOR_DENIED');if(!signatures.includes(m.signature))throw new Error('PLUGIN_SIGNATURE_DENIED');const perms=[...new Set(m.permissions||[])];for(const p of perms)if(!ALLOWED_PERMISSIONS.has(p))throw new Error(`PLUGIN_PERMISSION_DENIED:${p}`);return{...m,permissions:perms.sort()};}
function scopedApi(api,permissions){const out=Object.create(null);for(const p of permissions){if(p==='project.read'&&api.projectRead)out.projectRead=(...a)=>api.projectRead(...a);if(p==='selection.read'&&api.selectionRead)out.selectionRead=(...a)=>api.selectionRead(...a);if(p==='command.propose'&&api.commandPropose)out.commandPropose=(...a)=>api.commandPropose(...a);if(p==='diagnostics.write'&&api.diagnosticsWrite)out.diagnosticsWrite=(...a)=>api.diagnosticsWrite(...a);}return Object.freeze(out);}
class PluginSandbox{constructor(options={}){this.hostVersion=options.hostVersion||'1.0.0';this.authors=options.authors||[];this.signatures=options.signatures||[];this.api=options.api||{};this.plugins=new Map();}
 register(manifest,plugin){const m=validateManifest(manifest,this);if(!plugin||typeof plugin.activate!=='function')throw new Error('PLUGIN_ENTRY_INVALID');this.plugins.set(m.id,{manifest:m,plugin,enabled:false,crashes:0});return m.id;}
 enable(id){const r=this.plugins.get(id);if(!r)throw new Error('PLUGIN_NOT_FOUND');try{const result=r.plugin.activate(scopedApi(this.api,r.manifest.permissions));r.enabled=true;r.result=result;return{status:'ENABLED',id};}catch(error){r.enabled=false;r.crashes++;r.lastError=String(error&&error.message||error);return{status:'DISABLED_AFTER_CRASH',id,error:r.lastError};}}
 disable(id){const r=this.plugins.get(id);if(!r)throw new Error('PLUGIN_NOT_FOUND');try{r.plugin.deactivate?.();}finally{r.enabled=false;}return{status:'DISABLED',id};}
 status(id){const r=this.plugins.get(id);if(!r)return null;return{id,enabled:r.enabled,crashes:r.crashes,permissions:[...r.manifest.permissions],lastError:r.lastError||null};}}
return Object.freeze({ALLOWED_PERMISSIONS,parseVersion,compatible,validateManifest,scopedApi,PluginSandbox});});
