(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurProjectRevisionAuditService=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const clone=v=>JSON.parse(JSON.stringify(v));
class ProjectRevisionAuditService{constructor(options={}){this.projects=new Map();this.revisions=new Map();this.audit=[];this.clock=options.clock||(()=>new Date().toISOString());this.seq=0;}
 _ctx(ctx){if(!ctx||!ctx.userId||!ctx.tenantId)throw new Error('SERVICE_AUTH_REQUIRED');return{userId:String(ctx.userId),tenantId:String(ctx.tenantId),roles:[...(ctx.roles||[])]};}
 _event(type,ctx,data){this.audit.push(Object.freeze({id:`AUD${++this.seq}`,type,tenantId:ctx.tenantId,userId:ctx.userId,at:this.clock(),data:clone(data)}));}
 _row(id,ctx){const p=this.projects.get(String(id));if(!p)throw new Error('PROJECT_NOT_FOUND');if(p.tenantId!==ctx.tenantId)throw new Error('PROJECT_RLS_DENIED');return p;}
 create(input,context){const ctx=this._ctx(context),id=String(input.id||`P${++this.seq}`);if(this.projects.has(id))throw new Error('PROJECT_DUPLICATE');const row={id,tenantId:ctx.tenantId,name:String(input.name||''),version:0,createdBy:ctx.userId,createdAt:this.clock()};this.projects.set(id,row);this.revisions.set(id,[]);this._event('PROJECT_CREATED',ctx,{id});return clone(row);}
 list(context){const ctx=this._ctx(context);return[...this.projects.values()].filter(x=>x.tenantId===ctx.tenantId).map(clone);}
 appendRevision(projectId,payload,options={}){const ctx=this._ctx(options.context),p=this._row(projectId,ctx),expected=Number(options.expectedVersion);if(!Number.isInteger(expected)||expected!==p.version)throw new Error('REVISION_CONFLICT');const data=clone(payload);const rev=Object.freeze({id:`${p.id}-R${p.version+1}`,projectId:p.id,tenantId:p.tenantId,number:p.version+1,payload:data,createdBy:ctx.userId,createdAt:this.clock()});this.revisions.get(p.id).push(rev);p.version++;this._event('REVISION_APPENDED',ctx,{projectId:p.id,revisionId:rev.id,number:rev.number});return clone(rev);}
 readRevision(projectId,number,context){const ctx=this._ctx(context);this._row(projectId,ctx);const r=(this.revisions.get(String(projectId))||[]).find(x=>x.number===Number(number));if(!r)throw new Error('REVISION_NOT_FOUND');return clone(r);}
 auditLog(context){const ctx=this._ctx(context);return this.audit.filter(x=>x.tenantId===ctx.tenantId).map(clone);}
 resetLocal(options={}){if(options.environment!=='local-test'||options.confirmed!==true)throw new Error('LOCAL_RESET_FORBIDDEN');this.projects.clear();this.revisions.clear();this.audit.length=0;this.seq=0;return{status:'RESET',environment:'local-test'};}}
return Object.freeze({ProjectRevisionAuditService});});
