(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurReviewWorkflow=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';const clone=v=>JSON.parse(JSON.stringify(v));const ROLES=Object.freeze({VIEWER:[],COMMENTER:['COMMENT'],REVIEWER:['COMMENT','RESOLVE','REOPEN'],APPROVER:['COMMENT','RESOLVE','REOPEN','APPROVE']});
function allowed(role,action){return(ROLES[String(role||'').toUpperCase()]||[]).includes(action);}
class ReviewWorkflow{constructor(options={}){this.items=new Map();this.audit=[];this.clock=options.clock||(()=>new Date().toISOString());this.seq=0;}
 _event(type,actor,payload){const e=Object.freeze({id:`A${++this.seq}`,type,actor:String(actor||''),at:this.clock(),payload:clone(payload)});this.audit.push(e);return e;}
 comment(input,ctx={}){if(!allowed(ctx.role,'COMMENT'))throw new Error('REVIEW_PERMISSION_DENIED');if(!input||!input.targetId||!String(input.body||'').trim())throw new Error('REVIEW_COMMENT_INVALID');const id=`C${++this.seq}`,item={schema:'plmr-review-item-v1',id,target:{entityId:String(input.targetId),ownerId:String(input.ownerId||'')},body:String(input.body).trim(),status:'OPEN',createdBy:String(ctx.userId||''),createdAt:this.clock(),export:false};this.items.set(id,item);this._event('COMMENT_CREATED',ctx.userId,{id,target:item.target});return clone(item);}
 _transition(id,status,action,ctx){if(!allowed(ctx.role,action))throw new Error('REVIEW_PERMISSION_DENIED');const item=this.items.get(id);if(!item)throw new Error('REVIEW_NOT_FOUND');if(item.status===status)throw new Error('REVIEW_STATE_UNCHANGED');item.status=status;item.updatedAt=this.clock();item.updatedBy=String(ctx.userId||'');this._event(`COMMENT_${status}`,ctx.userId,{id});return clone(item);}
 resolve(id,ctx={}){return this._transition(id,'RESOLVED','RESOLVE',ctx);}reopen(id,ctx={}){return this._transition(id,'OPEN','REOPEN',ctx);}
 approve(revisionId,ctx={}){if(!allowed(ctx.role,'APPROVE'))throw new Error('REVIEW_PERMISSION_DENIED');if([...this.items.values()].some(x=>x.status==='OPEN'))throw new Error('REVIEW_OPEN_COMMENTS');const a={schema:'plmr-approval-v1',revisionId:String(revisionId||''),status:'APPROVED',by:String(ctx.userId||''),at:this.clock()};this._event('REVISION_APPROVED',ctx.userId,a);return Object.freeze(a);}
 list(){return[...this.items.values()].map(clone);}auditLog(){return this.audit.map(clone);}sceneEntities(){return this.list().map(x=>Object.freeze({id:`REVIEW_${x.id}`,semantic:'review',targetId:x.target.entityId,status:x.status,export:false,layer:'PLMR_UI_REVIEW'}));}}
return Object.freeze({ROLES,allowed,ReviewWorkflow});});
