(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurP3DVBridge=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const SCHEMA='plmr-p3dv-bridge-v1';
const WORKSPACE_SCHEMA='plmr-p3dv-workspace-v1';
const MESSAGE_SCHEMA='plmr-p3dv-runtime-message-v1';
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function color(v,fallback){const s=String(v||fallback||'').trim();if(!/^RAL\s?\d{4}(?:\s+(?:MAT|PARLAK|TEXTURE))?$/i.test(s)&&!/^#[0-9a-f]{6}$/i.test(s))throw new Error('P3DV_COLOR_INVALID');return s.toUpperCase();}
function build(project,scene,options={}){if(!project||!scene)throw new Error('P3DV_INPUT_REQUIRED');const nodes=(scene.nodes||scene.entities||[]).filter(n=>n&&n.export!==false).map((n,i)=>Object.freeze({id:String(n.id||`N${i+1}`),ownerId:String(n.ownerId||n.instanceId||'ROOT'),productType:String(n.productType||project.productType||'UNKNOWN'),view:String(n.view||'MODEL'),transform:clone(n.transform||{x:0,y:0,z:0,rotation:0}),bounds:clone(n.bounds||null),material:{system:color(n.systemColor||options.systemColor,'RAL 7016 MAT'),panel:color(n.panelColor||options.panelColor,'RAL 9016 MAT'),glass:String(n.glassColor||options.glassColor||'FÜME')},sourceEntityIds:[...(n.sourceEntityIds||[n.id]).filter(Boolean).map(String)]}));const max=Number(options.maxNodes)||5000;if(nodes.length>max)throw new Error('P3DV_MODEL_TOO_LARGE');const selection=Object.fromEntries(nodes.flatMap(n=>n.sourceEntityIds.map(id=>[id,n.id])));return Object.freeze({schema:SCHEMA,version:1,direction:'PLMR_TO_P3DV_ONLY',project:{id:String(project.id||''),revision:Number(project.revision)||0,productType:String(project.productType||'')},nodes:Object.freeze(nodes),selection:Object.freeze(selection),readOnly:true});}
function validate(pkg){const errors=[];if(!pkg||pkg.schema!==SCHEMA)errors.push('SCHEMA');if(pkg&&pkg.direction!=='PLMR_TO_P3DV_ONLY')errors.push('DIRECTION');if(pkg&&pkg.readOnly!==true)errors.push('READ_ONLY');for(const n of pkg&&pkg.nodes||[]){if(!n.id||!n.ownerId)errors.push('IDENTITY');for(const v of Object.values(n.transform||{}))if(typeof v==='number'&&!Number.isFinite(v))errors.push('COORDINATE');}return Object.freeze({ok:errors.length===0,errors:Object.freeze([...new Set(errors)])});}
function sanitizeRuntimeSnapshot(snapshot){if(!snapshot||typeof snapshot!=='object')return null;const source=clone(snapshot);if(source.schema&&source.schema!=='p3dv-host-snapshot-v1')throw new Error('P3DV_WORKSPACE_SNAPSHOT_SCHEMA');return source;}
function createWorkspace(input={}){return Object.freeze({schema:WORKSPACE_SCHEMA,productId:String(input.productId||''),productGroup:String(input.productGroup||''),snapshot:sanitizeRuntimeSnapshot(input.snapshot),updatedAt:String(input.updatedAt||new Date().toISOString())});}
function createRuntimeMessage(type,payload={}){return Object.freeze({schema:MESSAGE_SCHEMA,source:'plmr-unified-host',type:String(type||''),payload:clone(payload)});}
function validateRuntimeMessage(message){return !!(message&&message.schema===MESSAGE_SCHEMA&&message.source==='plmr-unified-host'&&typeof message.type==='string');}
// Legacy scene reverse-write remains forbidden. PLMR V14.02 only persists an opaque
// P3DV runtime snapshot under ProjectModel.workspaces; it never mutates PLMR 2D
// geometry through this legacy scene bridge.
function receiveFromP3DV(){throw new Error('P3DV_REVERSE_WRITE_FORBIDDEN');}
return Object.freeze({SCHEMA,WORKSPACE_SCHEMA,MESSAGE_SCHEMA,color,build,validate,sanitizeRuntimeSnapshot,createWorkspace,createRuntimeMessage,validateRuntimeMessage,receiveFromP3DV});});
