(function(root){
'use strict';
const SCHEMA='plmr-ai-geometry-validation-v1';
const EPS=0.01;
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const finite=v=>Number.isFinite(Number(v));
function normalizeBounds(b){if(root.PulumurSceneGraph&&root.PulumurSceneGraph.normalizeBounds)return root.PulumurSceneGraph.normalizeBounds(b);if(!b||![b.minX,b.minY,b.maxX,b.maxY].every(finite))return null;const minX=Math.min(Number(b.minX),Number(b.maxX)),minY=Math.min(Number(b.minY),Number(b.maxY)),maxX=Math.max(Number(b.minX),Number(b.maxX)),maxY=Math.max(Number(b.minY),Number(b.maxY));return {minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY};}
function close(a,b,tolerance){return Math.abs(Number(a)-Number(b))<=Math.max(EPS,Number(tolerance)||EPS);}
function metric(code,pass,expected,actual,evidence){return Object.freeze({code,pass:Boolean(pass),expected:clone(expected),actual:clone(actual),evidence:Object.freeze(evidence||{})});}
function canonicalEntity(entity){const numeric={};['x','y','x1','y1','x2','y2','w','h','r','radius','rotation','height','width'].forEach(k=>{if(entity&&finite(entity[k]))numeric[k]=Number(entity[k]);});['p1','p2','dimLine','points'].forEach(k=>{if(entity&&Array.isArray(entity[k]))numeric[k]=clone(entity[k]);});return {type:String(entity&&entity.type||'UNKNOWN').toUpperCase(),layer:String(entity&&entity.layer||'0').toUpperCase(),ownerId:String(entity&&entity.ownerId||entity&&entity.ownerInstance||''),productType:String(entity&&entity.productType||''),viewId:String(entity&&entity.viewId||''),numeric};}
function signature(entities){return (entities||[]).map(canonicalEntity).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));}
function expectedBoundsFromProposal(proposal){const p=proposal||{};if(p.expectedBounds)return normalizeBounds(p.expectedBounds);if(finite(p.width)&&finite(p.height))return normalizeBounds({minX:0,minY:0,maxX:Number(p.width),maxY:Number(p.height)});if(finite(p.width)&&finite(p.depth))return normalizeBounds({minX:0,minY:0,maxX:Number(p.width),maxY:Number(p.depth)});return null;}
function dimensionsFromDrawing(drawing){const values=[];(drawing&&drawing.entities||[]).forEach((e,index)=>{if(String(e.type||'').toLowerCase()==='dimension'){const value=finite(e.value)?Number(e.value):finite(e.measurement)?Number(e.measurement):null;if(value!==null)values.push({index,value,ownerId:e.ownerId||e.ownerInstance||null});}});return values;}
function validate(input,options){const source=input||{},drawing=source.drawing,proposal=source.proposal||source.draft||{},tol=Number(options&&options.tolerance)||EPS,metrics=[],findings=[];if(!drawing||!Array.isArray(drawing.entities))return Object.freeze({schema:SCHEMA,status:'FAIL',productionReady:false,metrics:Object.freeze([metric('DRAWING_REQUIRED',false,true,false)]),findings:Object.freeze(['DRAWING_REQUIRED']),visualSimilarityAccepted:false});const actualBounds=normalizeBounds(drawing.bounds);const expectedBounds=expectedBoundsFromProposal(proposal);metrics.push(metric('BOUNDS_VALID',!!actualBounds,'finite bounds',actualBounds));if(expectedBounds&&actualBounds){const widthPass=close(expectedBounds.width,actualBounds.width,tol),heightPass=close(expectedBounds.height,actualBounds.height,tol);metrics.push(metric('BOUNDS_WIDTH_EQUIVALENCE',widthPass,expectedBounds.width,actualBounds.width,{tolerance:tol}));metrics.push(metric('BOUNDS_HEIGHT_EQUIVALENCE',heightPass,expectedBounds.height,actualBounds.height,{tolerance:tol}));}
const dims=dimensionsFromDrawing(drawing),expectedDims=Array.isArray(proposal.dimensions)?proposal.dimensions.map(Number).filter(Number.isFinite):[];if(expectedDims.length){const actual=dims.map(d=>d.value);const pass=expectedDims.every(v=>actual.some(a=>close(a,v,tol)));metrics.push(metric('DIMENSION_EQUIVALENCE',pass,expectedDims,actual,{tolerance:tol}));}else metrics.push(metric('DIMENSION_ENTITIES_MEASURED',true,'optional',dims));
let scene;try{scene=drawing.sceneGraph||(root.PulumurSceneGraph&&root.PulumurSceneGraph.createFromDrawing(drawing,source.context||{}));}catch(error){findings.push(`SCENE_GRAPH:${error.message}`);}const entityNodes=scene&&root.PulumurSceneGraph?root.PulumurSceneGraph.entityNodes(scene):[];const ownerFailures=entityNodes.filter(n=>n.exportable&&(!n.ownerId||!n.productType||!n.instanceId));metrics.push(metric('OWNER_EQUIVALENCE',ownerFailures.length===0,0,ownerFailures.length,{entityIds:ownerFailures.map(n=>n.entityId)}));const sceneExport=scene&&root.PulumurSceneGraph?root.PulumurSceneGraph.exportEntities(scene):(drawing.entities||[]).filter(e=>e.exportable!==false&&e.uiOnly!==true&&e.type!=='interaction');let prepared=drawing;try{prepared=root.PulumurExportService?root.PulumurExportService.prepareDrawing(root.PulumurSceneGraph&&scene?root.PulumurSceneGraph.toDrawing(scene,'export',drawing):drawing):drawing;}catch(error){findings.push(`EXPORT_PREPARE:${error.message}`);}const exportSig=signature(prepared.entities||[]),sceneSig=signature(sceneExport);metrics.push(metric('EXPORT_ENTITY_EQUIVALENCE',JSON.stringify(exportSig)===JSON.stringify(sceneSig),sceneSig,exportSig,{sceneCount:sceneSig.length,exportCount:exportSig.length}));const uiLeaked=(prepared.entities||[]).filter(e=>e.uiOnly===true||e.layoutNeutral===true||e.type==='interaction');metrics.push(metric('EXPORT_UI_EXCLUSION',uiLeaked.length===0,0,uiLeaked.length));if(root.PulumurConstraintEngine){const constraints=root.PulumurConstraintEngine.evaluate({project:source.project,drawing});const errors=constraints.filter(f=>f.severity==='ERROR');metrics.push(metric('CONSTRAINT_ENGINE',errors.length===0,0,errors.length,{errors}));}
const failed=metrics.filter(m=>!m.pass);failed.forEach(m=>findings.push(m.code));return Object.freeze({schema:SCHEMA,status:failed.length?'FAIL':'PASS',productionReady:failed.length===0,metrics:Object.freeze(metrics),findings:Object.freeze(findings),visualSimilarityAccepted:false,explanation:Object.freeze({summary:failed.length?'Gerçek geometri veya export sözleşmesi eşleşmedi.':'Gerçek geometri, owner ve export sözleşmeleri eşleşti.',failed:Object.freeze(failed.map(m=>m.code))})});}
function validateClosedLoop(input,options){const source=input||{};if(typeof source.buildDrawing!=='function')throw new TypeError('GEOMETRY_BUILD_CALLBACK_REQUIRED');const drawing=source.buildDrawing(clone(source.proposal||source.draft||{}));const result=validate({...source,drawing},options);return Object.freeze({...result,drawingGenerated:true,iteration:1,autoMutationPerformed:false});}
const api=Object.freeze({SCHEMA,normalizeBounds,canonicalEntity,signature,validate,validateClosedLoop});root.PulumurAiGeometryValidator=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
