(function(root){
'use strict';
const SCHEMA='plmr-ai-project-draft-v1';
const PRODUCT_MAP=[[/freedom/i,'BCUBE_FREEDOM'],[/pergo\s*rise|pergola/i,'PERGO_RISE'],[/giyotin/i,'GUILLOTINE'],[/zip|perde/i,'ZIP_SCREEN'],[/sürme/i,'SLIDING']];
function num(value){return Number(String(value).replace(',','.'));}
function toMm(value,unit){const n=num(value);if(!Number.isFinite(n))return NaN;if(!unit||unit.toLowerCase()==='mm')return n;if(unit.toLowerCase()==='cm')return n*10;if(unit.toLowerCase()==='m')return n*1000;return NaN;}
function parseDimensions(text){const match=String(text||'').match(/(\d+(?:[.,]\d+)?)\s*(mm|cm|m)?\s*[x×]\s*(\d+(?:[.,]\d+)?)\s*(mm|cm|m)?/i);if(!match)return null;const unit1=match[2]||match[4]||'mm',unit2=match[4]||match[2]||'mm';return {width:toMm(match[1],unit1),depth:toMm(match[3],unit2),source:match[0],units:[unit1,unit2]};}
function parse(text){const raw=String(text||'').trim(),errors=[],ambiguities=[];if(!raw)return Object.freeze({schema:SCHEMA,status:'REJECTED',errors:['COMMAND_EMPTY'],ambiguities:[],draft:null});if(/\b(inch|inç|ft|feet|yard)\b/i.test(raw))errors.push('UNIT_UNSUPPORTED');const dims=parseDimensions(raw);if(!dims||![dims.width,dims.depth].every(Number.isFinite))errors.push('DIMENSIONS_REQUIRED');const products=PRODUCT_MAP.filter(([re])=>re.test(raw)).map(([,id])=>id);let host=products.includes('BCUBE_FREEDOM')?'BCUBE_FREEDOM':products.includes('PERGO_RISE')?'PERGO_RISE':null;const opening=products.find(id=>['SLIDING','GUILLOTINE','ZIP_SCREEN'].includes(id))||null;if(!host&&!opening)ambiguities.push('PRODUCT_REQUIRED');if(products.filter(id=>['BCUBE_FREEDOM','PERGO_RISE'].includes(id)).length>1)errors.push('HOST_PRODUCT_CONFLICT');const rail=raw.match(/(\d+)\s*ray/i);if(rail&&opening!=='SLIDING')errors.push('RAIL_OPTION_WITHOUT_SLIDING');const direction=/\bsağ(a)?\b/i.test(raw)?'RIGHT':/\bsol(a)?\b/i.test(raw)?'LEFT':null;const view=/ön\s*cephe/i.test(raw)?'FRONT':/arka\s*cephe/i.test(raw)?'REAR':/yan\s*cephe/i.test(raw)?'SIDE':'DEFAULT';if(opening&&!view)ambiguities.push('PLACEMENT_VIEW_REQUIRED');const status=errors.length?'REJECTED':ambiguities.length?'NEEDS_CLARIFICATION':'VALID';const draft={hostProduct:host,openingProduct:opening,width:dims&&dims.width,depth:dims&&dims.depth,placementView:view,options:{railCount:rail?Number(rail[1]):undefined,direction}};return Object.freeze({schema:SCHEMA,status,errors:Object.freeze(errors),ambiguities:Object.freeze(ambiguities),draft:Object.freeze(draft),raw});}
function dryRun(result,validator){if(!result||result.schema!==SCHEMA||result.status!=='VALID')return Object.freeze({valid:false,errors:['DRAFT_NOT_VALID'],result});if(typeof validator!=='function')return Object.freeze({valid:true,errors:[],result});const response=validator(result.draft)||{};return Object.freeze({valid:response.valid!==false,errors:Object.freeze(response.errors||[]),result});}
function apply(result,context,callback){if(!result||result.schema!==SCHEMA||result.status!=='VALID')throw new Error('DRAFT_NOT_VALID');if(!context||context.approved!==true)throw new Error('DRAFT_APPROVAL_REQUIRED');if(typeof callback!=='function')throw new TypeError('DRAFT_APPLY_CALLBACK_REQUIRED');return callback(JSON.parse(JSON.stringify(result.draft)));}
const api=Object.freeze({SCHEMA,parse,parseDimensions,dryRun,apply});root.PulumurNaturalLanguageDraft=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
