(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurReleaseOperations=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
function version(v){const m=String(v||'').match(/^(\d+)\.(\d+)(?:\.(\d+))?$/);if(!m)throw new Error('RELEASE_VERSION_INVALID');return m.slice(1).map(x=>Number(x||0));}
function compare(a,b){const x=version(a),y=version(b);for(let i=0;i<3;i++)if(x[i]!==y[i])return x[i]-y[i];return 0;}
function cleanInstall(files,{required=['index.html','src/app.js','sw.js','manifest.webmanifest']}={}){const set=new Set(files||[]);const missing=required.filter(x=>!set.has(x));return{status:missing.length?'FAIL':'PASS',missing,required:[...required]};}
function upgradePlan({from,to,migrations=[],backupChecksum}={}){if(compare(from,to)>=0)throw new Error('UPGRADE_DIRECTION_INVALID');if(!backupChecksum)throw new Error('UPGRADE_BACKUP_REQUIRED');const ordered=[...migrations].sort((a,b)=>compare(a.from,b.from));let current=from,steps=[];while(compare(current,to)<0){const step=ordered.find(x=>x.from===current&&compare(x.to,to)<=0);if(!step)throw new Error(`UPGRADE_PATH_MISSING:${current}`);steps.push({...step});current=step.to;}if(current!==to)throw new Error('UPGRADE_TARGET_UNREACHED');return{schema:'plmr-upgrade-plan-v1',from,to,backupChecksum,steps,dryRun:true,requiresConfirmation:true};}
function rollbackPlan({checkpoint,sha256,currentVersion,targetVersion}={}){if(!checkpoint||!/^[a-f0-9]{64}$/i.test(sha256||''))throw new Error('ROLLBACK_CHECKPOINT_INVALID');if(compare(targetVersion,currentVersion)>=0)throw new Error('ROLLBACK_DIRECTION_INVALID');return{schema:'plmr-rollback-plan-v1',checkpoint,sha256,currentVersion,targetVersion,verifyBeforeRestore:true,requiresConfirmation:true};}
function docsAudit(entries,{exists=()=>true}={}){const required=['installation','upgrade','rollback','admin','user','security'];const by=new Map((entries||[]).map(x=>[x.id,x]));const missing=required.filter(id=>!by.has(id));const broken=(entries||[]).filter(x=>!x.path||!exists(x.path)).map(x=>x.id);return{status:missing.length||broken.length?'FAIL':'PASS',missing,broken,count:(entries||[]).length};}
function trainingAudit({demos=[],lessons=[],roles=[]}={}){const missing=[];if(demos.length<3)missing.push('DEMO_PROJECTS');if(!lessons.some(x=>x.topic==='draw-export'))missing.push('DRAW_EXPORT_LESSON');for(const role of ['user','admin','support'])if(!roles.includes(role))missing.push(`ROLE_${role.toUpperCase()}`);return{status:missing.length?'FAIL':'PASS',missing,demoCount:demos.length,lessonCount:lessons.length};}
function operationsChecklist(input={}){const checks=['releaseTests','packageManifest','backup','rollbackDryRun','docs','training','manualCad'].map(id=>({id,pass:input[id]===true}));return{schema:'plmr-rc-operations-v1',checks,status:checks.every(x=>x.pass)?'READY':'BLOCKED',featureFreeze:true};}
return Object.freeze({version,compare,cleanInstall,upgradePlan,rollbackPlan,docsAudit,trainingAudit,operationsChecklist});});
