(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurAccessibilityI18nMobile=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const DICTS=Object.freeze({tr:Object.freeze({save:'Kaydet',exportPdf:'PDF İndir',exportDxf:'DXF İndir',zoomIn:'Yakınlaştır',zoomOut:'Uzaklaştır',selected:'Seçildi'}),en:Object.freeze({save:'Save',exportPdf:'Download PDF',exportDxf:'Download DXF',zoomIn:'Zoom in',zoomOut:'Zoom out',selected:'Selected'})});
function language(code){const x=String(code||'tr').toLowerCase().split('-')[0];return DICTS[x]?x:'tr';}
function translate(key,code='tr',vars={}){const lang=language(code);let value=DICTS[lang][key]??DICTS.tr[key]??String(key);for(const [k,v] of Object.entries(vars))value=value.replaceAll(`{${k}}`,String(v));return value;}
function accessibleControl({role='button',label,pressed,expanded,disabled=false}={}){if(!label)throw new Error('ACCESSIBLE_NAME_REQUIRED');const out={role,'aria-label':String(label),tabindex:disabled?-1:0};if(pressed!==undefined)out['aria-pressed']=String(!!pressed);if(expanded!==undefined)out['aria-expanded']=String(!!expanded);if(disabled)out['aria-disabled']='true';return out;}
function keyboardActivate(event,activate){if(!event||typeof activate!=='function')return false;if(event.key==='Enter'||event.key===' '){event.preventDefault?.();activate();return true;}return false;}
function focusOrder(items){return(items||[]).filter(x=>!x.disabled&&!x.hidden).sort((a,b)=>(a.tabIndex??0)-(b.tabIndex??0)||(a.order??0)-(b.order??0)).map(x=>x.id);}
function luminance(hex){const v=String(hex).replace('#','');if(!/^[0-9a-f]{6}$/i.test(v))throw new Error('COLOR_INVALID');const c=[0,2,4].map(i=>parseInt(v.slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4));return .2126*c[0]+.7152*c[1]+.0722*c[2];}
function contrast(a,b){const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
function createViewport({scale=1,minScale=.25,maxScale=8,x=0,y=0}={}){let state={scale,x,y};const clamp=s=>Math.max(minScale,Math.min(maxScale,s));return Object.freeze({get:()=>({...state}),wheel(delta,anchor={x:0,y:0}){const next=clamp(state.scale*(delta<0?1.1:.9));const ratio=next/state.scale;state={scale:next,x:anchor.x-(anchor.x-state.x)*ratio,y:anchor.y-(anchor.y-state.y)*ratio};return{...state};},pinch(startDistance,endDistance,center={x:0,y:0}){if(!(startDistance>0&&endDistance>0))throw new Error('PINCH_DISTANCE_INVALID');const next=clamp(state.scale*endDistance/startDistance);const ratio=next/state.scale;state={scale:next,x:center.x-(center.x-state.x)*ratio,y:center.y-(center.y-state.y)*ratio};return{...state};},pan(dx,dy){state={...state,x:state.x+Number(dx||0),y:state.y+Number(dy||0)};return{...state};},reset(){state={scale:1,x:0,y:0};return{...state};}});}
function liveMessage(text,priority='polite'){return{role:priority==='assertive'?'alert':'status','aria-live':priority,textContent:String(text||'')};}
return Object.freeze({DICTS,language,translate,accessibleControl,keyboardActivate,focusOrder,contrast,createViewport,liveMessage});});
