(function(root){'use strict';const SCHEMA='plmr-command-palette-v1';const clone=v=>JSON.parse(JSON.stringify(v));
function normalizeShortcut(v){return String(v||'').trim().toLowerCase().split('+').map(x=>x.trim()).filter(Boolean).sort((a,b)=>{const o=['ctrl','meta','alt','shift'];return (o.indexOf(a)<0?99:o.indexOf(a))-(o.indexOf(b)<0?99:o.indexOf(b))||a.localeCompare(b)}).join('+');}
class CommandPalette{constructor(options={}){this.commands=new Map();this.shortcuts=new Map();this.macros=new Map();this.executor=options.executor||null;this.transaction=options.transaction||null;}
 register(c){if(!c||!c.id||typeof c.run!=='function')throw new Error('PALETTE_COMMAND_INVALID');if(c.public!==true)throw new Error('PALETTE_PUBLIC_COMMAND_REQUIRED');if(this.commands.has(c.id))throw new Error('PALETTE_COMMAND_DUPLICATE');const item=Object.freeze({...c,keywords:Object.freeze([...(c.keywords||[])])});this.commands.set(c.id,item);if(c.shortcut)this.bindShortcut(c.id,c.shortcut);return item;}
 bindShortcut(id,shortcut){if(!this.commands.has(id))throw new Error('PALETTE_COMMAND_UNKNOWN');const key=normalizeShortcut(shortcut);if(!key)throw new Error('PALETTE_SHORTCUT_INVALID');if(this.shortcuts.has(key)&&this.shortcuts.get(key)!==id)throw new Error('PALETTE_SHORTCUT_CONFLICT');this.shortcuts.set(key,id);return key;}
 search(q,ctx={}){const s=String(q||'').toLocaleLowerCase('tr-TR');return [...this.commands.values()].filter(c=>(!c.permission||ctx.permissions?.includes(c.permission))&&[c.id,c.title,...c.keywords].join(' ').toLocaleLowerCase('tr-TR').includes(s));}
 execute(id,payload,ctx={}){const c=this.commands.get(id);if(!c)throw new Error('PALETTE_COMMAND_UNKNOWN');if(c.permission&&!ctx.permissions?.includes(c.permission))throw new Error('PALETTE_PERMISSION_DENIED');return c.run(clone(payload||{}),ctx);}
 saveMacro(name,steps){const n=String(name||'').trim();if(!n)throw new Error('PALETTE_MACRO_NAME_REQUIRED');if(this.macros.has(n))throw new Error('PALETTE_MACRO_DUPLICATE');const clean=(steps||[]).map(s=>{const c=this.commands.get(s.commandId);if(!c||c.public!==true)throw new Error('PALETTE_MACRO_COMMAND_NOT_PUBLIC');return Object.freeze({commandId:s.commandId,payload:clone(s.payload||{})});});const m=Object.freeze({schema:SCHEMA,name:n,steps:Object.freeze(clean)});this.macros.set(n,m);return m;}
 runMacro(name,ctx={}){const m=this.macros.get(name);if(!m)throw new Error('PALETTE_MACRO_UNKNOWN');const run=()=>m.steps.map(s=>this.execute(s.commandId,s.payload,ctx));return this.transaction?this.transaction(`Makro: ${name}`,run):run();}}
const api=Object.freeze({SCHEMA,normalizeShortcut,CommandPalette});root.PulumurCommandPalette=api;if(typeof module!=='undefined')module.exports=api;})(typeof window!=='undefined'?window:globalThis);
