(function(root){
  'use strict';
  function boot(){
    const api=root.PulumurProjectWizard;if(!api||typeof document==='undefined')return null;
    const $=id=>document.getElementById(id);const dialog=$('projectWizardDialog'),open=$('startWizardBtn');if(!dialog||!open)return null;
    const wizard=api.create({storage:root.localStorage});wizard.restore();
    const steps=['Proje','Ürün','Pozlar','Kontrol'];
    const productLabels=Object.freeze({PERGO_RISE:'Pergola',P3DV_ROLLING_ROOF:'Rolling Roof (Retractable)',P3DV_BIOCLIMATIC:'Bioclimatic (Tilt)',P3DV_ECO_BIOCLIMATIC:'Eco-Bioclimatic (Tilt)',SLIDING:'Sürme',GUILLOTINE:'Giyotin',ZIP_SCREEN:'Zip Perde'});
    const productLabel=value=>productLabels[String(value||'').toUpperCase()]||String(value||'');
    function render(){const d=wizard.getDraft(),step=d.stepIndex;$('wizardStepLabel').textContent=`${step+1}/4 · ${steps[step]}`;dialog.querySelectorAll('[data-wizard-step]').forEach(el=>el.hidden=Number(el.dataset.wizardStep)!==step);$('wizardBackBtn').disabled=step===0;$('wizardNextBtn').hidden=step===3;$('wizardCompleteBtn').hidden=step!==3;
      $('wizardCustomer').value=d.project.customerName;$('wizardProject').value=d.project.projectName;$('wizardProduct').value=d.productType;$('wizardPositions').innerHTML=d.positions.map((p,i)=>`<div class="wizard-position" data-id="${p.id}"><strong>${p.positionNo}</strong><label>Genişlik<input data-field="width" type="number" min="1" value="${p.width}"></label><label>Yükseklik<input data-field="height" type="number" min="1" value="${p.height}"></label><label>Açılım<input data-field="projection" type="number" min="1" value="${p.projection}"></label><button type="button" data-remove ${d.positions.length===1?'disabled':''}>Sil</button></div>`).join('');$('wizardReview').textContent=`${d.project.customerName||'-'} · ${d.project.projectName||'-'}\n${productLabel(d.productType)}\n${d.positions.length} poz: ${d.positions.map(p=>`${p.positionNo} ${p.width}×${p.height}`).join(', ')}`;$('wizardMessage').textContent='';
    }
    function sync(){wizard.updateProject({customerName:$('wizardCustomer').value,projectName:$('wizardProject').value});wizard.setProduct($('wizardProduct').value);}
    open.addEventListener('click',()=>{render();dialog.showModal();});$('wizardCloseBtn').addEventListener('click',()=>dialog.close());$('wizardResetBtn').addEventListener('click',()=>{wizard.reset();render();});$('wizardBackBtn').addEventListener('click',()=>{sync();wizard.back();render();});$('wizardNextBtn').addEventListener('click',()=>{sync();const r=wizard.next();if(!r.valid){$('wizardMessage').textContent=r.errors[0];return;}render();});$('wizardAddPositionBtn').addEventListener('click',()=>{wizard.addPosition();render();});
    $('wizardPositions').addEventListener('input',e=>{const host=e.target.closest('[data-id]');if(!host)return;wizard.updatePosition(host.dataset.id,{[e.target.dataset.field]:Number(e.target.value)});});$('wizardPositions').addEventListener('click',e=>{const btn=e.target.closest('[data-remove]');if(!btn)return;wizard.removePosition(btn.closest('[data-id]').dataset.id);render();});
    $('wizardCompleteBtn').addEventListener('click',()=>{sync();const r=wizard.complete();if(!r.valid){$('wizardMessage').textContent=r.errors[0];return;}const o=r.output;const set=(id,value,event='input')=>{const el=$(id);if(el){el.value=value;el.dispatchEvent(new Event(event,{bubbles:true}));}};set('systemCount',o.systemCount);set('width',o.widthInput);set('height',o.height);set('projection',o.projection);(()=>{const host=$('product');let target=o.productType;if(o.productType==='PERGO_RISE'&&host){target=Array.from(host.options).some(x=>x.value==='Pergo Rise')?'Pergo Rise':(Array.from(host.options).some(x=>x.value==='PERI01')?'PERI01':o.productType);}set('product',target,'change');})();root.sessionStorage&&root.sessionStorage.setItem('plmr_project_wizard_last_output_v1',JSON.stringify(o));dialog.close();const start=$('startNewProjectBtn');if(start)start.click();setTimeout(()=>{set('newProjectCustomer',o.projectInfo.customerName);set('newProjectName',o.projectInfo.projectName);},0);document.dispatchEvent(new CustomEvent('plmr:wizard:complete',{detail:o}));});render();return wizard;
  }
  root.PulumurProjectWizardController=Object.freeze({boot});if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}
})(typeof window!=='undefined'?window:globalThis);
