(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PulumurHitTestEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=v=>JSON.parse(JSON.stringify(v));
function screenToWorld(point,view={}){const z=Number(view.zoom)||1;if(!Number.isFinite(z)||z<=0)throw new Error('HIT_ZOOM_INVALID');return{x:(Number(point.x)-(Number(view.panX)||0))/z,y:(Number(point.y)-(Number(view.panY)||0))/z};}
function distanceToSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return Math.hypot(p.x-a.x,p.y-a.y);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));}
function candidateDistance(p,e){if(e.type==='POINT')return Math.hypot(p.x-e.x,p.y-e.y);if(e.type==='LINE')return distanceToSegment(p,e.start,e.end);const b=e.bounds;if(b){const dx=Math.max(b.minX-p.x,0,p.x-b.maxX),dy=Math.max(b.minY-p.y,0,p.y-b.maxY);return Math.hypot(dx,dy);}return Infinity;}
function hitTest(entities,screenPoint,options={}){const p=screenToWorld(screenPoint,options.view);const pointer=options.pointerType||'mouse';const px=pointer==='touch'?(options.touchRadius||18):(options.mouseRadius||6);const radius=px/(Number(options.view&&options.view.zoom)||1);const priority=options.priority||['dimension','profile','product','geometry'];return (entities||[]).filter(e=>e&&e.visible!==false&&e.interactive!==false).map(e=>({...e,distance:candidateDistance(p,e)})).filter(e=>e.distance<=radius).sort((a,b)=>a.distance-b.distance||priority.indexOf(a.kind)-priority.indexOf(b.kind)||String(a.id).localeCompare(String(b.id))).map(clone);}
function cycleSelection(candidates,currentId){if(!candidates.length)return null;const i=candidates.findIndex(x=>x.id===currentId);return clone(candidates[(i+1)%candidates.length]);}
function snap(point,entities,options={}){const radius=Number(options.radius)||10;const modes=options.modes||['endpoint','midpoint'];const spots=[];for(const e of entities||[]){if(e.type!=='LINE')continue;if(modes.includes('endpoint')){spots.push({mode:'endpoint',point:e.start,entityId:e.id});spots.push({mode:'endpoint',point:e.end,entityId:e.id});}if(modes.includes('midpoint'))spots.push({mode:'midpoint',point:{x:(e.start.x+e.end.x)/2,y:(e.start.y+e.end.y)/2},entityId:e.id});}for(const s of spots)s.distance=Math.hypot(point.x-s.point.x,point.y-s.point.y);spots.sort((a,b)=>a.distance-b.distance||a.mode.localeCompare(b.mode));return spots[0]&&spots[0].distance<=radius?clone(spots[0]):null;}
function interactionEntity(entity){return Object.freeze({...clone(entity),layer:'PLMR_UI_INTERACTION',semantic:'interaction',export:false});}
return Object.freeze({screenToWorld,distanceToSegment,hitTest,cycleSelection,snap,interactionEntity});});
